### ISSUE TITLE
Not enough colors specified in visualise.py

### ISSUE THREAD

**Issue by JKunst** [responsible-business-decision-making/trbs#25]
Hi heroes, 
I really enjoyed seeing the notebook and looking through the code again. Unbelievable what you made out of it, looks great!

When creating the visualisation I noticed there might not be enough colors available?
![image](https://github.com/responsible-business-decision-making/trbs/assets/10348491/2baf54b5-d22d-47c6-815d-5a53a7ac7421)

But seriously, amazing!

Kind regards, and say hi to all the butterflies.
Jasper

**Comment by thomivarvandijk** [comment]
Hi Jasper, 

Welcome back!

We will add this to our backlog, but our color picker expert (=you) has left the team. 

Regards, 
The Vlinders
