### ISSUE TITLE
Differentiate the coloring in the table visualization for STB key outputs

### ISSUE THREAD

**Issue by ymmath** [responsible-business-decision-making/trbs#9]
In the table example below, we want the colour to reflect the favourable output, which in the case of STB key outputs such as 'CO2 emission' we want the darkest shade to be 'Focus on wind turbines'.

![image](https://github.com/responsible-business-decision-making/trbs/assets/81219735/928ec30f-4b5b-4115-a11f-49993adb46b4)

**Comment by christianvijfvinkel** [comment]
Complex to add STB column to output table. This issue will be solved in a later stage.

**Comment by thomivarvandijk** [comment]
Closing issue due to complexity and low prio
